### ISSUE TITLE
Uncaught ReferenceError: AmCharts is not defined

### ISSUE THREAD

**Issue by olahat90** [amcharts/ammap3#13]
Hi
angular2 I would like to use it in his case. Local development there is not a trouble, on the other hand a mistake wrote a message in the title when I create a packet with the help of webpack I receive it, I rehearsed it already in all ways, but he manages to solve it in no way.
For somebody possibly idea?

**Comment by martynasma** [comment]
Hi there,

I suggest you take a look here:

https://github.com/amcharts/amcharts3-angular2

It's our official Angular2 plugin. You will find examples and usage instructions there.

**Comment by olahat90** [comment]
Thank you for the answer.

It was not a solution unfortunately. I realised that the webpack does not really like it meanwhile the minify files, it was necessary to modify it so.

**Comment by adityashukla74** [comment]
I am facing the same issue with Systemjs! What to do? I have already mapped the umd.js
<img width="1280" alt="screen shot 2017-06-20 at 8 39 34 pm" src="https://user-images.githubusercontent.com/11692248/27340645-a059059c-55f8-11e7-8b39-6351eae8928c.png">

**Comment by Pauan** [comment]
@adityashukla74 Make sure that you are loading AmCharts with `<script>` tags in your HTML file:

```
<script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
<script src="https://www.amcharts.com/lib/3/serial.js"></script>
<script src="https://www.amcharts.com/lib/3/themes/light.js"></script>
```

**Comment by AleksejDix** [comment]
why would you load them in the html file, how can i do the same if i want to bundle them

**Comment by Pauan** [comment]
@AleksejDix You can't bundle them.

The export plugin dynamically loads files based upon the base URL, so you must use `<script>` tags.

**Comment by igasparetto** [comment]
In the case you are using Angular Client:
.angular-cli.json

       "scripts": [

        "../node_modules/amcharts3/amcharts/amcharts.js",

        "../node_modules/amcharts3/amcharts/serial.js",

        "../node_modules/amcharts3/amcharts/themes/light.js",
