### ISSUE TITLE
TypeError: d.AmMap is not a constructor

### ISSUE THREAD

**Issue by sahilbhatia** [amcharts/ammap3#15]
Hi,

I want to use AmCharts with React JS (ES6 + Webpack) in my project. For that, I am following the instructions listed on the official [amcharts3-react github page](https://github.com/amcharts/amcharts3-react).

Using `npm`, I have installed:
- amcharts3 from 'amcharts/amcharts3'
- amcharts3-react from 'amcharts/amcharts3-react'

Then, I imported `AmCharts` like this: `import AmCharts from 'amcharts3-react';`

**NOTE:** I am able to implement [Simple Column Chart](https://www.amcharts.com/demos/simple-column-chart/) example.

Finally, when I tried to implement the [Custom HTML Elements as Map Markers](https://www.amcharts.com/demos/custom-html-elements-map-markers/) example in React, I am getting the following error:

```
TypeError: d.AmMap is not a constructor

d.makeChart http://localhost:3002/static/js/bundle.js:63246:224
AmCharts.React<.componentDidMount http://localhost:3002/static/js/bundle.js:64198:17
ReactCompositeComponent.mountComponent/</< http://localhost:3002/static/js/bundle.js:26212:21
measureLifeCyclePerf http://localhost:3002/static/js/bundle.js:26022:13
ReactCompositeComponent.mountComponent/< http://localhost:3002/static/js/bundle.js:26211:12
notifyAll http://localhost:3002/static/js/bundle.js:18461:10
ON_DOM_READY_QUEUEING.close http://localhost:3002/static/js/bundle.js:29443:6
TransactionImpl.closeAll http://localhost:3002/static/js/bundle.js:19673:12
TransactionImpl.perform http://localhost:3002/static/js/bundle.js:19620:12
batchedMountComponentIntoNode http://localhost:3002/static/js/bundle.js:31591:4
TransactionImpl.perform http://localhost:3002/static/js/bundle.js:19607:14
ReactDefaultBatchingStrategy.batchedUpdates http://localhost:3002/static/js/bundle.js:29010:15
batchedUpdates http://localhost:3002/static/js/bundle.js:18224:11
ReactMount._renderNewRootComponent http://localhost:3002/static/js/bundle.js:31785:6
ReactMount._renderSubtreeIntoContainer http://localhost:3002/static/js/bundle.js:31866:22
ReactMount.render http://localhost:3002/static/js/bundle.js:31887:13
<anonymous> http://localhost:3002/static/js/bundle.js:10931:2
__webpack_require__ http://localhost:3002/static/js/bundle.js:556:12
hotCreateRequire/fn http://localhost:3002/static/js/bundle.js:87:20
<anonymous> http://localhost:3002/static/js/bundle.js:591:19
__webpack_require__ http://localhost:3002/static/js/bundle.js:556:12
<anonymous> http://localhost:3002/static/js/bundle.js:579:18
<anonymous> http://localhost:3002/static/js/bundle.js:1:11
```

I saw a [similar issue](https://github.com/amcharts/amcharts3/issues/18) filed under `amcharts/amcharts3` library. However, they have closed the issue saying that it should filed in `AmMap` repository.

Can anyone please help me out with this?

**Comment by Pauan** [comment]
@sahilbhatia When using a non-serial type, you must import the appropriate file.

You should be able to fix it by following these directions:

1. You must install the `ammap3` package by using `npm install --save amcharts/ammap3`

2. You must import it by using this code:

   ```
   import AmCharts from 'amcharts3-react';
   import 'ammap3/ammap/ammap.js';
   ```

   **Important:** the `ammap` import must be below the `amcharts3-react` import.
