### ISSUE TITLE
Firefox Performance Issue

### ISSUE THREAD

**Issue by mether** [amcharts/ammap3#2]
Was doing some cross browser testing with my custom map based on the [Custom HTML Map Markers](https://www.amcharts.com/demos/custom-html-elements-map-markers/) demo included on the AMCHARTS website and I noticed that Firefox (running the latest version 44.0.2) has major performance issues when zooming in and out. 

I then checked out the [original demo](https://www.amcharts.com/demos/custom-html-elements-map-markers/) on the site and the same performance issue of a low framerate zoom and the background map disappearing and reappearing on zoom. Tested it on OSX 10.11.3 and Windows 8.

Any help would be much appreciated :)

**Comment by martynasma** [comment]
Sorry for not getting back earlier; your post slipped through the cracks.

The thing is that Firefox' SVG rendered is considerably slower than the one used in Webkit-based browsers like Chrome or Safari.

When zooming in, the map needs to be redrawn a number of times at various intermediate resolutions, which makes it look slow on Firefox.

There's little we can do about it, I'm afraid. If the performance of Firefox animation is not suitable, you may try detecting this browser and disabling animations altogether.
