### ISSUE TITLE
 MapLine/MapImage deletObject() method doesn't seem to be deleting the entry from map 'dataProvider' cache.

### ISSUE THREAD

**Issue by digrich** [amcharts/ammap3#22]
In my use case, I have to add and remove multiple MapLine and MapImage objects dynamically. For removal, I am looking up the object by Id ( map.getObjectById(id) ) and then calling delete function ( object.deletObject() ) to it. 

Though it removes the object from map, 'map.dataProvider.lines' size keeps growing. Not sure if that is the right way of deleting any object from the map.

Over the period, I see memory leak also on the map, could be because of this.

**Comment by martynasma** [comment]
I'm trying to reproduce the issue here:

https://codepen.io/team/amcharts/pen/0715ca949202a084c332e094e6fd4713?editors=0010

I get empty `map.dataProvider.images` after removal of image.

Is it possible you are using some older version of JavaScript Maps?

**Comment by digrich** [comment]
When you try to add an image through API, you will notice the issue. 

var user_img = new AmCharts.MapImage();
  user_img.id = "test1";
  user_img.type = "circle";
  user_img.scale = 5;
  user_img.latitude = 0;
  user_img.longitude = 0;
  user_img.chart = map;
  
  map.dataProvider.images.push(user_img);
  user_img.validate();
  
  var obj = map.getObjectById("test1");
  console.log("Before - " + map.dataProvider.images.length);
  obj.deleteObject();
  console.log("After - " + map.dataProvider.images.length);

**Comment by digrich** [comment]
A few days back, we purchased the license so I assume chart is having the latest version.

**Comment by martynasma** [comment]
OK, I'm presuming you can't use `validateNow()` after adding image because you don't want the overhead of whole map re-initializing.

I worked out the following routine to make it work then:

```
function add() {
  var user_img = new AmCharts.MapImage();
  user_img.id = "test";
  user_img.type = "circle";
  user_img.scale = 5;
  user_img.latitude = 0;
  user_img.longitude = 0;
  user_img.chart = map;
  user_img.validate();
  map.dataProvider.images.push(user_img);
  map.imagesProcessor.allObjects.push(user_img);
  map.imagesProcessor.allSvgObjects.push(user_img.displayObject);
  user_img.parentArray = map.dataProvider.images;
  console.log(map.dataProvider.images);
}
```

Demo updated:
https://codepen.io/team/amcharts/pen/0715ca949202a084c332e094e6fd4713?editors=0010

Hope this helps.

**Comment by digrich** [comment]
Thanks @martynasma.

**Comment by martynasma** [comment]
You're welcome!
