### ISSUE TITLE
Branding link doesn't stick to bottom left corner

### ISSUE THREAD

**Issue by wkeithvan** [amcharts/ammap3#27]
When the map height is dynamically changed (for instance, keeping the map full window height as the window size changes), the branding link moves to undesired spots. It seems that the location for the branding link is determined by a set number of pixels from  the top as opposed to from the bottom, so if the map size grows, the branding link might end up in the middle of the map (or disappear if it is shrunk).

For code, I removed the height (`height: 500px;`) from the `#chartdiv` and added the following to the javascript:
```
function setMapHeight() {
  var height = $(window).height();
  $('#chartdiv').css('height', height + "px");
}

window.onload = function(event) {
	setMapHeight();
};

window.onresize = function(event) {
	setMapHeight();
};
```

Here is a jsFiddle (modified from the a demo created by your team - [link](https://www.amcharts.com/demos/animations-along-lines/)) that shows the undesired behavior - [jsFiddle](jsfiddle.net/wkeithvan/syfn7xz5/). To see the behavior on the jsFiddle, resize the output window to be small, run the code, then resize the output window to be larger. Here is a GIF of the [behavior in action](https://imgur.com/a/GnVxl).

**Comment by martynasma** [comment]
You're right. The position of branding link is set at the moment of map initialization and is not updated when container size changes.

I'm adding this to TODO list. If/when it gets fixed, I'll let you know.

Thanks!

**Comment by martynasma** [comment]
Hey,

This is fixed in 3.21.8 we just released.

Let me know if you are still having the issue after upgrading.

**Comment by wkeithvan** [comment]
Sweet... it looks good on my site now!

**Comment by wkeithvan** [comment]
Looks good on my site now. Feel free to close the issue.

**Comment by wkeithvan** [comment]
Looks good on my site now!
