### ISSUE TITLE
Slow Installation

### ISSUE THREAD

**Issue by buster95** [amcharts/ammap3#28]
do you can upload maps in another repository?? can be separated by country, this repository include all maps and when you install with bower are 25mb in files,
best regard thanks for development this library,

I have made my own maps, is very easy 👍

**Comment by martynasma** [comment]
Hi there, thanks!

Unfortunately, no. Maintaining separate repos for each country (most of whcih have only two maps each) would be a tremendous overhead in maintenance. Sorry.
