### ISSUE TITLE
Is AmMap supports Javascript Object configuration?

### ISSUE THREAD

**Issue by kevzlou7979** [amcharts/ammap3#29]
Hi there,

Reading this https://www.amcharts.com/kbase/your-first-ammap/ and looking in the tutorial https://codepen.io/team/amcharts/pen/b8fa37be1f3d3a67396c38e33efc47bb?editors=0010. Does AmMap supports Javascript Object configuration instead of JSON Only?

Best Regards,
Mark

**Comment by martynasma** [comment]
Yes it does.

Take a look at [this tutorial](https://www.amcharts.com/kbase/using-object-based-chart-setup/).

It's about charts, but the same principle applies to maps.

```
var map = new AmCharts.AmMap();
...
```

**Comment by kevzlou7979** [comment]
Thanks yeah, this is working fine on my side.
