### ISSUE TITLE
Animation along curved line doesn't work correctly.

### ISSUE THREAD

**Issue by n1tb1** [amcharts/ammap3#31]
Dear support,

I faced with a problem after 3.21.7 release (Arc drawing improved), when image object doesn't animate along curved line correctly, the line looks much better after this update, but image doesn't follow along full length line,

here is an example on jsfiddle:
https://jsfiddle.net/hh88euzd/6/

So we see 2 lines, but animation use only upper line,

Can you please advise how to fix it?

If it's impossible I have another way, animation worked fine below 3.21.7 release, but there was another problem that fixed in 3.21.8 release (Bug fix: MapImage with animateAlongLine=true was shown of a incorrect size for a moment before animating.), may be you can advise me how to fix image scale?

**Comment by martynasma** [comment]
Hi there,

This looks like a bug. I'm going to file it under our internal TODO.

Will let you know when it's fixed.

Sorry, can't provide an ETA on it, tho :(

**Comment by n1tb1** [comment]
Thanks for response,

I will wait for fix.

**Comment by n1tb1** [comment]
Hi Martynasma, do you have any news on this fix?

**Comment by martynasma** [comment]
Not yet. Sorry :(

**Comment by martynasma** [comment]
Hi there,

We have just released a new version (3.21.13) which should fix the issue.

Please don't hesitate to get back to us if the problem persists after upgrading.

**Comment by n1tb1** [comment]
Hi Martynasma, the problem is fixed, thanks, now image animates along the line.
