### ISSUE TITLE
Angular cli - Geojson

### ISSUE THREAD

**Issue by siddharth1903** [amcharts/ammap3#33]
How do i call chart.parseGeojson.. Using Angular cli.. The service doesn't seem to be having this method..

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33770**.
> (replying here will automatically notify amCharts support agent)

Hi there,

`parseGeojson` is not a built-in AmCharts method. The [vanilla JS demo you're likely referring to](https://www.amcharts.com/kbase/using-geojson-maps-amcharts/) simply attaches a custom made `parseGeojson` method to the `AmCharts` object for namespacing purposes. I'm not well versed in Angular but you'd have to define that function in your directive class somewhere (i.e. without the `AmCharts` modifier as it isn't required) so it is accessible to your map creation code.

I hope that clarifies things.

Best,

Anthony Piris
amCharts

**Comment by siddharth1903** [comment]
Oops My bad i didn't look at the Demo properly.. The moment i found this call on the AmCharts namespace the assumption was that it is vanilla :) and was looking to find this on typings.. 😥 Thanks a ton for the clarification

**Comment by amcharts** [comment]
> New comment from Zendesk by **Anthony Piris** on ticket **33770**.
> (replying here will automatically notify amCharts support agent)

You're very welcome. :)

Please don't hesitate to reach out to us again if you have any other questions.

Best,

Anthony Piris
amCharts
