### ISSUE TITLE
Map BalloonText is not working 

### ISSUE THREAD

**Issue by sumanth1801** [amcharts/ammap3#38]
Balloon Text is not working with 
amcharts3-react : "^3.1.0",
ammap3 : "^3.21.13"
and chrome version > 68.0

Below is the mapConfig (Balloon function and data provider  is populated programmatically )

{
    "type": "map",
    "theme": "light",
    "colorSteps": 10,

    "showBalloonOnSelectedObject": true,
    "useObjectColorForBalloon": true,
    "dataProvider": {
   	 "map": "usaLow",
   	 "areas": [ {
   	   id: "US",
   	   value: 444
    	}],
    "areasSettings": {
      "autoZoom": true,
      "balloonText": "test",
      "selectedColor": "#e45566",
      "colorSolid": "#003668",
      "rollOverColor": "#53699b",
      "bringForwardOnHover": true,
      "outlineColor":"rgba(0, 0, 0, 0.56)"
    },
    "valueLegend": {
      "right": "10",
      "minValue": "Minimum",
      "maxValue": "Maximum",
      "maxColumns": "1",
      "borderColor": "#A9A9A9"
    },
}

mapConfig.balloonLabelFunction = (mapObject, map) => {
                return `test`;
};

Balloon Text is working  in chrome versions < 64

**Comment by martynasma** [comment]
Balloon is not shown for areas that are not "active".

In your config you are using `usaLow` map, yet do not have any ids in your data to attach to any of the states.

So, either you need to add those, or you can add `"getAreasFromMap": true,` to your `dataProvider` to automatically activate all state areas.

```
"dataProvider": {
  "map": "usaLow",
  "getAreasFromMap": true,
},
```

The balloonFunction will work then.

Hope that makes sense.

**Comment by sumanth1801** [comment]
Thanks for the quick reply @martynasma 
The areas in the data provider object is populated with State values and the IDs
are matching as well. The state areas are active. (I've also tried setting getAreasFromMap attribute)

[{"id":"AK","value":261.66},{"id":"AL","value":0.0},{"id":"CA","value":0.0},{"id":"CO","value":0.0},{"id":"FL","value":0.0},{"id":"GA","value":0.0},{"id":"IL","value":0.0},{"id":"KS","value":0.0},{"id":"MI","value":0.0},{"id":"MO","value":0.0},{"id":"MS","value":0.0},{"id":"NC","value":0.0},{"id":"ND","value":0.0},{"id":"NH","value":0.0},{"id":"NJ","value":0.0},{"id":"NY","value":0.0},{"id":"OR","value":0.0},{"id":"PA","value":0.0},{"id":"SC","value":4.27},{"id":"SD","value":0.0},{"id":"TN","value":4.75},{"id":"TX","value":4.69},{"id":"UT","value":272.0},{"id":"VA","value":0.0},{"id":"WA","value":0.0},{"id":"WV","value":0.0}]

balloonLabelFunction(returns value) is getting triggered everytime we hover over the state.  
However, balloon text is not being displayed.

Chrome Version : 69.0.3497.100 (Official Build) (64-bit)

**Comment by martynasma** [comment]
State IDs are a bit different. They are prefixed with the "US-" as per ISO standard recommendations.

So it should be "US-AK", instead of "AK", etc.

**Comment by sumanth1801** [comment]
I was using node version : 6.x
Issue got resolved once I upgraded to latest node version.
