### ISSUE TITLE
Wrong Coordinate

### ISSUE THREAD

**Issue by Uter1007** [amcharts/ammap3#39]
Hi,

I've found some coordinate issues (On Google Maps: https://www.google.com/maps/place/Yanfeng+S.A.+Automotive+Interior+Systems+(Pty)+Ltd/@-33.0611705,27.8468234,16.75z/data=!4m5!3m4!1s0x0:0xbbbba8562f2834af!8m2!3d-33.0601736!4d27.8510003). 

When I am adding these coordinates on http://www.amcharts.com/lib/3/maps/ & zooming into it the point is clearly away from the surface and into the water. 

Behavior is also on the Detail Card of South Africa.. So What can we do do calibrate it correctly ? 

Cheers,
Christoph

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **39827**.
> (replying here will automatically notify amCharts support agent)

Hi Christoph,

The vector maps that are used by amCharts have reduced detail. We could have fine detail, but it would make map files super large, which is not good.

When map simplification occurs, a number of points are removed, losing some detail in the process and somewhat distorting the lines, especially coastal ones.

This is especially prominent when zoomed in.

What you can do is following:

1) If you are using low-detail version of the map (worldLow), try switching to worldHigh. It has more detail. Chances are, it might solve the issue.

2) Manually adjust the coordinates of the marker so it is further inland.

I hope you find this useful.

Let me know if you have questions.

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by Uter1007** [comment]
Thx - we alternated \ tweaked the coordinates so it fits.
