### ISSUE TITLE
Strange 3d effect on russia / moscow city

### ISSUE THREAD

**Issue by Uter1007** [amcharts/ammap3#42]
https://www.amcharts.com/svg-maps/?map=russia

When you zoom to moscow city the borders look like a 3d effect, to generate more depth. Problem is that with other color schemes, it look like double lines. It's the only area that I found such effect, is it possible to get a version without it ? 

Cheers,
Christoph

**Comment by Uter1007** [comment]
![image](https://user-images.githubusercontent.com/3653245/48015304-1cecf480-e129-11e8-9212-8f68e25e039f.png)

**Comment by martynasma** [comment]
Thanks for bringing it to our attention.

Will let you know when updated map is available.

**Comment by amcharts** [comment]
> New comment from Zendesk by **Martynas Majeris** on ticket **40416**.
> (replying here will automatically notify amCharts support agent)

Hi there,

We have 

Yours sincerely,

Martynas Majeris
amCharts

P.S. have you seen upcoming amCharts 4 yet?
https://www.amcharts.com/v4

**Comment by martynasma** [comment]
We have updated Russian maps here:
https://www.amcharts.com/svg-maps/?map=russia

They are also updated in the CDN.

Will also be included with the next release of JavaScript Maps.

Thanks!

**Comment by Uter1007** [comment]
awesome - many thx !

**Comment by martynasma** [comment]
I'm closing this, but please feel free to post any follow up questions you may have.

**Comment by Uter1007** [comment]
the only question that I have left - is it possible to update the js map in the repository as well ? cheers ;)

**Comment by martynasma** [comment]
This repo is updated once new version of amMap is released.

However, since I'm not sure when that is going to happen, I'll see if I can commit just the maps.

**Comment by martynasma** [comment]
Done.
