### ISSUE TITLE
xyChart Heatmap conditional formatting adapters

### ISSUE THREAD

**Issue by Frostbytez05** [amcharts/ammap3#45]
Hello as the title suggests I'm currently working on a xyChart heatmap but I'm having some difficulty. My chart is very similar to the chart below but I need to use 3 colors green, yellow, red for 0 - 100%. I found that using adapters I can get this done but I'm having difficulty with implementing one as I keep getting "template is not defined" I may be doing this incorrectly. I wanted to ask if I could get an example of how I could implement conditional formatting on a xy heatmap?

https://codepen.io/team/amcharts/pen/BrOeRz

**Comment by martynasma** [comment]
Would you like to post that on amCharts 4 repo? :)

https://github.com/amcharts/amcharts4/issues

**Comment by awmctx** [comment]
Oh I'm sorry, yes I'll post it on amCharts 4

Thank you so much Martynas for pointing this out to me,

Best regards,
Alex Windelberg
