### ISSUE TITLE
Images are not found after change DataProvider

### ISSUE THREAD

**Issue by ambrous** [amcharts/ammap3#7]
Hi!

I have added animation like this https://www.amcharts.com/demos/animations-along-lines/

Then I change dataProvider array and call validateData():

```
dataProvider.images = dataProvider.images;
dataProvider.lines = dataProvider.lines;
validateData();
```
but I have error:

`Uncaught TypeError: Cannot read property 'segments' of undefined`

in

`d.MapImage.d.Class.update`

do i do something wrong?

**Comment by martynasma** [comment]
I can't seem to be able to reproduce this error. Here's my test map:

https://codepen.io/team/amcharts/pen/23124aa8e58743bb57dd4ec08d79044e?editors=0010

Press the "test" button.

Or are you doing something differently?

**Comment by ambrous** [comment]
I changed your sample: http://codepen.io/ambrous/pen/BQNbwy

Error seems to arise when dateProvider is fill difference data.

**Comment by martynasma** [comment]
Hi there,

Sorry for the wait.

It must be a bug. When you are replacing the whole of the lines/images in the data porovider, some processes continue trying to animate previous ones, causing errors.

We'll let you know when the fix is available.

**Comment by martynasma** [comment]
Thanks for hanging in.

The issue has been fixed in:
https://github.com/amcharts/ammap3/releases/tag/3.20.19
